// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA79C5G4duVt6ji1Ssbqq_NMo-0FdyVx6g',
    appId: '1:88928166311:web:f5703e7f09e2e37276d682',
    messagingSenderId: '88928166311',
    projectId: 'agenda-digital-e481b',
    authDomain: 'agenda-digital-e481b.firebaseapp.com',
    storageBucket: 'agenda-digital-e481b.appspot.com',
    measurementId: 'G-ZKX41R170W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkT6ekOHDBmsAsplEdPVXYoTtp1Blw2dw',
    appId: '1:88928166311:android:b409f6b81d1b6a8376d682',
    messagingSenderId: '88928166311',
    projectId: 'agenda-digital-e481b',
    storageBucket: 'agenda-digital-e481b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYO6qHLdeKLA__XzOzMdxAdqc2ujIwI3w',
    appId: '1:88928166311:ios:d46e2a1d192f6d1b76d682',
    messagingSenderId: '88928166311',
    projectId: 'agenda-digital-e481b',
    storageBucket: 'agenda-digital-e481b.firebasestorage.app',
    iosBundleId: 'com.example.agendaDigital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYO6qHLdeKLA__XzOzMdxAdqc2ujIwI3w',
    appId: '1:88928166311:ios:d46e2a1d192f6d1b76d682',
    messagingSenderId: '88928166311',
    projectId: 'agenda-digital-e481b',
    storageBucket: 'agenda-digital-e481b.firebasestorage.app',
    iosBundleId: 'com.example.agendaDigital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA79C5G4duVt6ji1Ssbqq_NMo-0FdyVx6g',
    appId: '1:88928166311:web:7b8ca21132d46ef576d682',
    messagingSenderId: '88928166311',
    projectId: 'agenda-digital-e481b',
    authDomain: 'agenda-digital-e481b.firebaseapp.com',
    storageBucket: 'agenda-digital-e481b.firebasestorage.app',
    measurementId: 'G-J2YTGH57S5',
  );

}